services:
    app:
        build: .
        ports: 
            - "8000:80"
            - "8001:443"
        depends_on:
            - db
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: 8001
            ASPNETCORE_Kestrel__Certificates__Default__Password: W@llet123
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/wallet-dev.pfx"
        volumes:
            - ~/.aspnet/https:/https/
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Pwd12345!"
            ACCEPT_EULA: "Y"
