services:
    app:
        build: .
        ports: 
            - "8000:80"
            - "4433:443"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Pwd12345!"
            ACCEPT_EULA: "Y"
